server:
  servlet:
    context-path: /hitic/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hitic
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

ocr:
  api:
    url: https://api.ocr.space/parse/image